ProjetoWEB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/urls.py
from django.urls import path
from .views import *

# path('endereco/', MinhaView.as_view(), name='nome-da-url'),
urlpatterns = [
    path('', InicioView.as_view(), name='index'),
    path('inicio', Inicio1View.as_view(), name='index1'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('parceria/', ParceriaView.as_view(), name='parceria'),  
    path('acervo/<int:pk>/', LivroInfoView.as_view(), name='info-livro'), 
    path('filtroLivro/', LivroFiltroView.as_view(), name='filtro-livro'),
    path('desenvolvedor/', DesenvolvedorView.as_view(), name='desenvolvedor'),
    path('satisfacaoUsuario/', SatisfacaoUserView.as_view(), name='satisfacaoUser'),
    path('satisfacaoBiblioteca/', SatisfacaoBibliView.as_view(), name='satisfacaoBibli'),
    path('faleConosco/', FaleConoscoView.as_view(), name='faleConosco'),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField

class Autor(models.Model):
    nome = models.CharField(max_length=70)
    curriculo_lattes = models.CharField(max_length=16, verbose_name="Currículo Lattes", null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self): #toString in Java
        return "{}".format(self.nome)
    
class Genero(models.Model):
    descricao = models.CharField(max_length=20, verbose_name="Descrição")

    def __str__(self): 
        return "{}".format(self.descricao)
  
     
class Categoria(models.Model):
    genero = models.ForeignKey(Genero, on_delete=models.PROTECT, null=True) 
    descricao = models.CharField(max_length=20, verbose_name="Descrição")

    def __str__(self): 
        return "{}".format(self.descricao)   
    
class Livro(models.Model):
    isbn = models.CharField(max_length=13, null=True, blank=True)
    edicao = models.IntegerField(default=1, verbose_name="Edição", null=True, blank=True)
    titulo = models.CharField(max_length=100)
    autor = models.ForeignKey(Autor, on_delete=models.PROTECT) #Proteger exclusão de tabelas relacionadas
    ano = models.CharField(max_length=4)
    editora = models.CharField(max_length=40, null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT, null=True)
    num_page = models.IntegerField(verbose_name="Nº Páginas", null=True, blank=True)
    capa = ResizedImageField(
        size=[200,292],
        quality=80,
        default='../static/img/sem_capa.jpg',
        upload_to='img/', 
        null=False, 
        blank=False
    )
    resumo = models.TextField(default="Resumo da Obra")
    consulta = models.PositiveIntegerField(default=1)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
   
    def __str__(self): 
        return "{} - {}".format(self.titulo, self.autor.nome)
    
class Acervo(models.Model):
    livro = models.ForeignKey(Livro, on_delete=models.PROTECT)
    qtdeExemplar = models.IntegerField(verbose_name="Qtde. do Material", default=1)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    
    def __str__(self): 
        return "{} - {}".format(self.livro.titulo, self.qtdeExemplar)

paginas/models.py
from django.db import models

# Create your models here.

paginas/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from cadastros.models import *
from django.views.generic.list import ListView
from django.db.models import Q

# Create your views here.

#class ModeloView(TemplateView): #Herança - Extends em Java
#    template_name = "paginas/modelo.html"
    
class InicioView(ListView):
    model = Acervo
    template_name = "paginas/index.html"
    paginate_by = 10
      
    def get_queryset(self):
        s = self.request.GET.get('seach')
        if s:
            multiple_q = Q(Q(livro__titulo__icontains=s) |
                           Q(livro__autor__nome__icontains=s) | Q(livro__editora__icontains=s) | Q(livro__categoria__descricao__icontains=s))
            acervos = Acervo.objects.filter(multiple_q)
        else:
            acervos = Acervo.objects.all()
        return acervos
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['livro_list'] = Acervo.objects.all().order_by("-id")#Ordenar com base no último cadastro
        return context
    
class LivroInfoView (TemplateView):
    template_name = "paginas/info-livro.html"  

    def get_context_data(self, **kwargs):
        context = super(LivroInfoView, self).get_context_data(**kwargs)
        acervos = Acervo.objects.get(pk=self.kwargs.get('pk'))
        acervos.livro.consulta += 1
        acervos.livro.save()
        context['acervo'] = acervos
        return context

class LivroFiltroView (ListView):
    template_name = "paginas/filtro-livro.html"
   
class PesquisarView (TemplateView):
    template_name = "pesquisar/pesquisar.html"     
    
class Inicio1View(TemplateView):
    template_name = "paginas/index1.html"
    
class SobreView(TemplateView):
    template_name = "paginas/sobre.html"
    
class ParceriaView(TemplateView):
    template_name = "paginas/parceria.html"
    
class DesenvolvedorView(TemplateView):
    template_name = "paginas/desenvolvedor.html"
    
class SatisfacaoUserView(TemplateView):
    template_name = "paginas/satisfacaoUser.html"
    
class SatisfacaoBibliView(TemplateView):
    template_name = "paginas/satisfacaoBibli.html"    
    
class FaleConoscoView(TemplateView):
    template_name = "paginas/faleConosco.html"
    
    

paginas/templates/paginas/desenvolvedor.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block titulo %}
    <title>EduTeca - Desenvolvedores</title>
{% endblock %}

{% block carrossel %}
{% endblock %}

{% block barra %}
{% endblock %}

{% block conteudo %}
        <div class="card bg-dark text-light text-justify m-auto col-11" style="padding: 20px;">
            <h1 align="center">Quem somos</h1>
            <p>
                O projeto EduTeca de integração dos Acervos das bibliotecas de
                Indaiatuba foi elaborado e desenvolvido por uma equipe altamente qualificada,
                especializada, e por último e não menos importante, amante da boa leitura.
            </p>
            <p>A equipe é composta pelo Lucas Dias Calado, Luís Fernando Bortolotti,
                Wesley Henrique Faveri De Oliveira, alunos do quarto semestre do curso de
                Análise e Desenvolvimento de Sistemas da Fatec-Indaiatuba.
            </p>
        </div>


    <!-- Parte opcional, se for deixar ACho que seria melhor tirar o segundo trecho do texto acima-->
    <br>
    <h2 style="text-align:center">Nosso time</h2>
    <div class="row">
        <div class="column">
            <div class="card bg-dark text-light text-sm-center">
                <img src="{% static 'img/personaWesley.bmp' %}" alt="Jane" style="border-radius: 5px;position: relative;height: 90%;width:90%;left: 5%;top: 15px;">
                <div class="container">
                    <br>
                    <h2 style="font-size:x-large;">Wesley Henrique Faveri</h2>
                    <p class="title">Analista de sistemas</p>
                    <p>wesley.henrique@eduteca.com</p>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="card bg-dark text-light text-sm-center">
                <img src="{% static 'img/personaLuis.bmp' %}" alt="Jane" style="border-radius: 5px;position: relative;height: 90%;width:90%;left: 5%;top: 15px;">
                <div class="container">
                    <br>
                    <h2 style="font-size:x-large;">Luis Fernando Bortolotti</h2>
                    <p class="title">Analista de sistemas</p>
                    <p>luis.fernando@eduteca.com</p>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="card bg-dark text-light text-sm-center">
                <img src="{% static 'img/personaLucas.bmp' %}" alt="Jane" style="border-radius: 5px;position: relative;height: 90%;width:90%;left: 5%;top: 15px;">
                <div class="container">
                    <br>
                    <h2 style="font-size: x-large;">Lucas Dias Calado</h2>
                    <p class="title">Analista de sistemas</p>
                    <p>lucas.dias@eduteca.com</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block carrosselCatalogo %}
{% endblock %}

{% block style %}
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
        }

        html {
            box-sizing: border-box;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        .column {
            float: left;
            width: 33.3%;
            margin-bottom: 16px;
            padding: 0 8px;
        }

        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            margin: 8px;
        }

        .about-section {
            padding: 50px;
            text-align: center;
            background-color: #474e5d;
            color: white;
        }

        .container {
            padding: 0 16px;
        }

        .container::after,
        .row::after {
            content: "";
            clear: both;
            display: table;
        }

        .title {
            color: grey;
        }

        .button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
        }

        .button:hover {
            background-color: #555;
        }

        @media screen and (max-width: 650px) {
            .column {
                width: 100%;
                display: block;
            }
        }
    </style>

{% endblock %}

paginas/templates/paginas/faleConosco.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
    <title>EduTeca - Ajuda</title>
{% endblock %}

{% block carrossel %}{% endblock %}

{% block barra %}{% endblock %}

{% block conteudo %}
    <div class="card text-light bg-dark text-justify m-auto col-11" style="padding: 20px;align-items: center;">
        <h2>
            Entre em contato e conheça o projeto: 
        </h2>
        <p>
            Entre em contato por meio do nosso formulário, possuímos uma equipe especialista 
            que irá atender e sanar dúvidas da melhor forma possível. E reforçando, assim como vocês, somos todos amantes da boa e velha leitura. 
        </p>
        <img src="{% static 'img/googleFormsICon.png' %}" alt="" style="width: 10%;">
        <br>
        <a style="font-size:x-large;width:100%;background-color: #2374e1;border-color: #2374e1;color: white;" href="https://forms.gle/1y8Ews1Mo9mPAmTK9" class="btn btn-light">INICIAR</a>
    </div>
{% endblock %}

{% block addcss %}
    <style>
        html {
            box-sizing: border-box;
        }
        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }
        .column {
            float: left;
            width: 33.3%;
            margin-bottom: 16px;
            padding: 0px;
        }
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            margin: 0px;
        }
        .about-section {
            padding: 50px;
            text-align: center;
            background-color: #474e5d;
            color: white;
        }
        .container {
            padding: 0 16px;
        }
        .container::after,
        .row::after {
            content: "";
            clear: both;
            display: table;
        }
        .title {
            color: grey;
        }
        .button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
        }
        .button:hover {
            background-color: #555;
        }
        @media screen and (max-width: 650px) {
            .column {
                width: 100%;
                display: block;
            }
        }
    </style>
{% endblock %}

paginas/templates/paginas/filtro-livro.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
    <title>EduTeca</title>
{% endblock %}

{% block barra %}
<li class="nav-item nav-link dropdown">
    <a  style="color: rgba(255,255,255,.55)" class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-bs-toggle="dropdown"
      aria-expanded="false">
      Gênero
    </a>
    <ul class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton">

      {% with ''|center:3 as range %}
      {% for x in range %}
      <!-- generos-->
        <li>
            <!-- inicio do botao do dropdown interno -->
            <a class="dropdown-item estilo-hover text-light" href="#">
                {{forloop.counter}} &raquo;
            </a>


            <ul class="dropdown-menu bg-dark text-light dropdown-submenu">
                {% with ''|center:3 as range2 %}
                {% for y in range2 %}
                    <!-- categorias-->

                    <!-- inicio dos itens do submenu -->

                    <li>
                        <a class="dropdown-item estilo-hover text-light"
                        href="http://127.0.0.1:8000/?titulo=exemplo {{forloop.counter}}">exemplo {{forloop.counter}}</a>
                    </li>

                {% endfor %}
                {% endwith %}
            </ul>

            <!-- fim do botao do dropdown interno -->

        </li>
        {% endfor %}
        {% endwith %}
    </ul>
</li>
<form action="?" method="GET">

    <input type="text" name="seach" id="" value="{{ request.GET.seach }}" class="p-1 border" autocomplete="off" placeholder="Título, Autor, Editora...">

    <button type="submit" class="btn btn-success">Buscar</button>

    <a href="{% url 'index' %}" class="btn btn-light">Limpar</a>

</form>
{% endblock %}

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{ user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

    <div class="container">  
        <div class="book-list">
            <hr>
            <h1 class="text-center">Filtro de Livros</h1>
            <hr>
            <div id="list-output" class="col-11 m-auto">
                <div class="row">

                    {% for f in livro_filtro %}
                    <h1>{{ l.categoria }}</h1>
                    <div class="row mt-4">
                        {% for a in l.acervo_set.all %}
                            <div class="col-6 m-auto">
                                <div class="row no-gutters bg-dark m-auto"style="left:0%;border-radius: 10px;">
                                        <div class=" card col-md-5 bg-dark" style="border-radius: 10px;max-width: 100%;max-height: 100%">
                                        <img src="{{ a.livro.capa.url }}" alt="" class="card-img center container-cards-item" style="position:relative;border-radius: 10px;top:0%;left:0%;height: 250px;width: 200px;max-width: 90%;max-height: 90%">
                                        </div>
                                        <div class="col-md-7 center-card">
                                            <div class="card-body bg-dark text-white center-card" style="font-size: small;position:relative;top:5%;right:0%;">
                                                <h5 class="card-title text-truncate" style="font-size: medium;" data-toggle="tooltip" title="{{ a.livro.titulo }}">{{ a.livro.titulo }}</h5>
                                                <p class="card-text text-truncate" data-toggle="tooltip" title="{{ a.livro.editora }}">Editora: {{ a.livro.editora }}</p>
                                                <p class="card-text text-truncate" data-toggle="tooltip" title="{{ a.livro.autor }}">Autor: {{ a.livro.autor }}</p>
                                                <a target="_blank" href="{% url 'info-livro' a.pk %}" class="btn btn-secondary m-auto zoom-bt" style=" border-color: #2374e1;background: #2374e1;font-size: medium;">Saiba Mais</a>
                                            </div>
                                        </div>
                                </div>
                                <br>
                            </div>
                        {% empty %}
                        <tr>
                            <td colspan="3"> Nenhum livro encontrado!</td>
                        </tr>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div> 
    </div>

    <ul class="pagination justify-content-center">
    
        {% if page_obj.has_previous %}

            {% if request.GET.nome %}
                <li class="page-item"><a class="page-link" href="?page=1&nome={{request.GET.nome}}">&laquo; Primeira</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&nome={{request.GET.nome}}">Anterior</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
            {% endif %}
        {% endif %}
    
        <li class="page-item">
            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span></li>
    
        {% if page_obj.has_next %}
            {% if request.GET.nome %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&nome={{request.GET.nome}}">Próxima</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&nome={{request.GET.nome}}">Última &raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
            {% endif %}
        {% endif %}
    </ul>
</div>
{% endblock %}

{% block addcss %}
<style>
    .book-list {
        margin-top: 50px;
        visibility: visible;
    }
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        width: 50%;
        height: 50%;
    }       
    .center-card {
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
    }       
</style>

{% endblock %}

paginas/templates/paginas/index.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
    <title>EduTeca</title>
{% endblock %}

{% block barra %}
<li class="nav-item nav-link dropdown">
    <a  style="color: rgba(255,255,255,.55)" class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-bs-toggle="dropdown"
      aria-expanded="false">
      Gênero
    </a>
    <ul class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton">

      {% with ''|center:3 as range %}
      {% for x in range %}
      <!-- generos-->
        <li>
            <!-- inicio do botao do dropdown interno -->
            <a class="dropdown-item estilo-hover text-light" href="#">
                {{forloop.counter}} &raquo;
            </a>


            <ul class="dropdown-menu bg-dark text-light dropdown-submenu">
                {% with ''|center:3 as range2 %}
                {% for y in range2 %}
                    <!-- categorias-->

                    <!-- inicio dos itens do submenu -->

                    <li>
                        <a class="dropdown-item estilo-hover text-light"
                        href="http://127.0.0.1:8000/?titulo=exemplo {{forloop.counter}}">exemplo {{forloop.counter}}</a>
                    </li>

                {% endfor %}
                {% endwith %}
            </ul>

            <!-- fim do botao do dropdown interno -->

        </li>
        {% endfor %}
        {% endwith %}
    </ul>
</li>
<form action="?" method="GET">

    <input type="text" name="seach" id="" value="{{ request.GET.seach }}" class="p-1 border" autocomplete="off" placeholder="Título, Autor, Editora...">

    <button type="submit" class="btn btn-success">Buscar</button>

    <a href="{% url 'index' %}" class="btn btn-light">Limpar</a>

</form>
{% endblock %}

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{ user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

    <div class="container">  
        <div class="book-list">
            <hr>
            <h1 class="text-center">Catálogo de Livros</h1>
            <hr>
            <div id="list-output" class="col-11 m-auto">
                <div class="row">
                    <div class="row mt-4">
                        {% for material in object_list %}
                            <div class="col-6 m-auto">
                                <div class="row no-gutters bg-dark m-auto"style="left:0%;border-radius: 10px;">
                                        <div class=" card col-md-5 bg-dark" style="border-radius: 10px;max-width: 100%;max-height: 100%">
                                        <img src="{{ material.livro.capa.url }}" alt="" class="card-img center container-cards-item" style="position:relative;border-radius: 10px;top:0%;left:0%;height: 250px;width: 200px;max-width: 90%;max-height: 90%">
                                        </div>
                                        <div class="col-md-7 center-card">
                                            <div class="card-body bg-dark text-white center-card" style="font-size: small;position:relative;top:5%;right:0%;">
                                                <h5 class="card-title text-truncate" style="font-size: medium;" data-toggle="tooltip" title="{{ material.livro.titulo }}">{{ material.livro.titulo }}</h5>
                                                <p class="card-text text-truncate" data-toggle="tooltip" title="{{ material.livro.editora }}">Editora: {{ material.livro.editora }}</p>
                                                <p class="card-text text-truncate" data-toggle="tooltip" title="{{ material.livro.autor }}">Autor: {{ material.livro.autor }}</p>
                                                <a target="_blank" href="{% url 'info-livro' material.pk %}" class="btn btn-secondary m-auto zoom-bt" style=" border-color: #2374e1;background: #2374e1;font-size: medium;">Saiba Mais</a>
                                            </div>
                                        </div>
                                </div>
                                <br>
                            </div>
                        {% empty %}
                        <tr>
                            <td colspan="3"> Nenhum livro encontrado!</td>
                        </tr>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div> 
    </div>

    <ul class="pagination justify-content-center">
    
        {% if page_obj.has_previous %}

            {% if request.GET.nome %}
                <li class="page-item"><a class="page-link" href="?page=1&nome={{request.GET.nome}}">&laquo; Primeira</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&nome={{request.GET.nome}}">Anterior</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
            {% endif %}
        {% endif %}
    
        <li class="page-item">
            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span></li>
    
        {% if page_obj.has_next %}
            {% if request.GET.nome %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&nome={{request.GET.nome}}">Próxima</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&nome={{request.GET.nome}}">Última &raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
            {% endif %}
        {% endif %}
    </ul>
</div>
{% endblock %}

{% block addcss %}
<style>
    .book-list {
        margin-top: 50px;
        visibility: visible;
    }
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        width: 50%;
        height: 50%;
    }       
    .center-card {
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
    }       
</style>

{% endblock %}

paginas/templates/paginas/parceria.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% block titulo %}
    <title>EduTeca - Parcerias</title>
{% endblock %}
{% block barra %}
{% endblock %}
{% block carrossel %}
{% endblock %}
{% block conteudo %}
  <div class="row row-cols-1 row-cols-md-3 g-4 col-11 m-auto">
    <div class="col">
      <div class="card bg-dark text-light" style="border-radius: 10px;">
        <img src="{% static 'img/biblioteca.jpg' %}" class="card-img-top" alt="..." style="position: relative;width: 90%;height: 90%;left: 5%;top: 15px;">
        <div class="card-body">
          <br>
          <h5 class="card-title">Biblioteca Rui Barbosa</h5>
          <p class="card-text">Endereço: R. das Primaveras, 450 - Vila Bergamo, Indaiatuba - SP, 13345-115.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card bg-dark text-light" style="border-radius: 10px;">
        <img src="{% static 'img/biblioteca1.jpg' %}" class="card-img-top" alt="..." style="position: relative;width: 90%;height: 90%;left: 5%;top: 15px;">
        <div class="card-body">
          <br>
          <h5 class="card-title">Biblioteca Laura Fahl Corrêa</h5>
          <p class="card-text">Endereço: R. Jordalino Pietro Bom, 1300 - Jd. Morada do Sol, Indaiatuba-SP, 13348-400.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card bg-dark text-light" style="border-radius: 10px;">
        <img src="{% static 'img/fatec.png' %}" class="card-img-top" alt="..." style="position: relative;width: 90%;height: 90%;left: 5%;top: 15px;">
        <div class="card-body">
          <br>
          <h5 class="card-title">Biblioteca - Fatec-ID</h5>
          <p class="card-text">Endereço: R. Dom Pedro I, 65 - Cidade Nova I, Indaiatuba - SP, 13334-100.</p>
        </div>
      </div>
    </div>
  </div>
  <br><br>
  <div class="col-md-10 mx-auto text-center" style="font-size: larger;">
      <p>
        Você é uma instituição e se interessou no projeto? 
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSdhLt-8aFDEtH0ILA47X4YTs9r72pwcUrZr4x4wejs-wo9ZYw/viewform?usp=sf_link">Venha participar também.</a>
      </p>
  </div>
{% endblock %}
{% block carrosselCatalogo %}
{% endblock %}

paginas/templates/paginas/satisfacaoBibli.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
    <title>Pesquisa de Satisfação</title>
{% endblock %}

{% block carrossel %}
{% endblock %}

{% block conteudo %}
    <br>
    <div class="card text-light bg-dark text-justify m-auto col-11" style="padding: 20px;align-items: center;">
      <h2>
        Pesquisa de satisfação
      </h2>
      <p>
        <a href="{% url 'sobre' %}">Conheça o projeto EduTeca</a>, com todos os recursos que nossa plataforma pode disponibilizar para a sua biblioteca. 
        Descubra e se conecte com todo nosso conteúdo e acervo. E por fim, reflita sobre o seguinte: “Como fiquei todo esse tempo sem estar 
        conectado com essa ferramenta?”. 
      </p>
      <p>
        Aproveite, e faça nossa pesquisa de satisfação, afinal nada melhor do que uma boa conversa franca para fazermos a melhor 
        plataforma já encontrada no segmento. Caso seja uma biblioteca, venha participar da nossa plataforma, e não deixe de colaborar com a sua opinião. 
      </p>
      <img src="{% static 'img/googleFormsICon.png' %}" alt="" style="width: 10%;">
      <br>
        <a style="font-size:x-large;width:100%;background-color: #2374e1;border-color: #2374e1;color: white;" href="https://docs.google.com/forms/d/e/1FAIpQLSdEmKUy76mPhT1GpGWFdOkfUF3yH_4DnivHyyg-KHUG7Kn4eg/viewform" class="btn btn-light">INICIAR</a>
      </div>
    </div>
{% endblock %}

{% block addcss %}
    <style>
        html {
            box-sizing: border-box;
        }
        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }
        @media screen and (max-width: 650px) {
            .column {
                width: 100%;
                display: block;
            }
        }
    </style>
{% endblock %}