ProjetoWEB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/urls.py
from django.urls import path
from .views import *

# path('endereco/', MinhaView.as_view(), name='nome-da-url'),
urlpatterns = [
    path('', InicioView.as_view(), name='index'),
    path('inicio', Inicio1View.as_view(), name='index1'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('parceria/', ParceriaView.as_view(), name='parceria'),  
    path('acervo/<int:pk>/', LivroInfoView.as_view(), name='info-livro'), 
    path('filtroLivro/', LivroFiltroView.as_view(), name='filtro-livro'),
    path('desenvolvedor/', DesenvolvedorView.as_view(), name='desenvolvedor'),
    path('satisfacaoUsuario/', SatisfacaoUserView.as_view(), name='satisfacaoUser'),
    path('satisfacaoBiblioteca/', SatisfacaoBibliView.as_view(), name='satisfacaoBibli'),
    path('faleConosco/', FaleConoscoView.as_view(), name='faleConosco'),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField

class Autor(models.Model):
    nome = models.CharField(max_length=70)
    curriculo_lattes = models.CharField(max_length=16, verbose_name="Currículo Lattes", null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self): #toString in Java
        return "{}".format(self.nome)
    
class Genero(models.Model):
    descricao = models.CharField(max_length=20, verbose_name="Descrição")

    def __str__(self): 
        return "{}".format(self.descricao)
  
     
class Categoria(models.Model):
    genero = models.ForeignKey(Genero, on_delete=models.PROTECT, null=True) 
    descricao = models.CharField(max_length=20, verbose_name="Descrição")

    def __str__(self): 
        return "{}".format(self.descricao)   
    
class Livro(models.Model):
    isbn = models.CharField(max_length=13, null=True, blank=True)
    edicao = models.IntegerField(default=1, verbose_name="Edição", null=True, blank=True)
    titulo = models.CharField(max_length=100)
    autor = models.ForeignKey(Autor, on_delete=models.PROTECT) #Proteger exclusão de tabelas relacionadas
    ano = models.CharField(max_length=4)
    editora = models.CharField(max_length=40, null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT, null=True)
    num_page = models.IntegerField(verbose_name="Nº Páginas", null=True, blank=True)
    capa = ResizedImageField(
        size=[200,292],
        quality=80,
        default='../static/img/sem_capa.jpg',
        upload_to='img/', 
        null=False, 
        blank=False
    )
    resumo = models.TextField(default="Resumo da Obra")
    consulta = models.PositiveIntegerField(default=1)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
   
    def __str__(self): 
        return "{} - {}".format(self.titulo, self.autor.nome)
    
class Acervo(models.Model):
    livro = models.ForeignKey(Livro, on_delete=models.PROTECT)
    qtdeExemplar = models.IntegerField(verbose_name="Qtde. do Material", default=1)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    
    def __str__(self): 
        return "{} - {}".format(self.livro.titulo, self.qtdeExemplar)

paginas/models.py
from django.db import models

# Create your models here.

paginas/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from cadastros.models import *
from django.views.generic.list import ListView
from django.db.models import Q

# Create your views here.

#class ModeloView(TemplateView): #Herança - Extends em Java
#    template_name = "paginas/modelo.html"
    
class InicioView(ListView):
    model = Acervo
    template_name = "paginas/index.html"
    paginate_by = 10
      
    def get_queryset(self):
        s = self.request.GET.get('seach')
        if s:
            multiple_q = Q(Q(livro__titulo__icontains=s) |
                           Q(livro__autor__nome__icontains=s) | Q(livro__editora__icontains=s) | Q(livro__categoria__descricao__icontains=s))
            acervos = Acervo.objects.filter(multiple_q)
        else:
            acervos = Acervo.objects.all()
        return acervos
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['livro_list'] = Acervo.objects.all().order_by("-id")#Ordenar com base no último cadastro
        return context
    
class LivroInfoView (TemplateView):
    template_name = "paginas/info-livro.html"  

    def get_context_data(self, **kwargs):
        context = super(LivroInfoView, self).get_context_data(**kwargs)
        acervos = Acervo.objects.get(pk=self.kwargs.get('pk'))
        acervos.livro.consulta += 1
        acervos.livro.save()
        context['acervo'] = acervos
        return context

class LivroFiltroView (ListView):
    template_name = "paginas/filtro-livro.html"
   
class PesquisarView (TemplateView):
    template_name = "pesquisar/pesquisar.html"     
    
class Inicio1View(TemplateView):
    template_name = "paginas/index1.html"
    
class SobreView(TemplateView):
    template_name = "paginas/sobre.html"
    
class ParceriaView(TemplateView):
    template_name = "paginas/parceria.html"
    
class DesenvolvedorView(TemplateView):
    template_name = "paginas/desenvolvedor.html"
    
class SatisfacaoUserView(TemplateView):
    template_name = "paginas/satisfacaoUser.html"
    
class SatisfacaoBibliView(TemplateView):
    template_name = "paginas/satisfacaoBibli.html"    
    
class FaleConoscoView(TemplateView):
    template_name = "paginas/faleConosco.html"
    
    

paginas/templates/paginas/rascunho/carroselCatalogo.html
{% block carrosselCatalogo %}
    <div class="container-cards">
      <h5 class="container-cards-title">Titulo</h5>
      <div class="container-cards-scroll">
        <div class="container-cards-item">
          <img src="{% static 'img\livro-furgeri.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-guerra-dos-tronos.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-machado-de-assis.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-manual-direito-penal.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-musashi.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-o-cacador-de-pipas.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-o-cortico.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-pmi-guide-book.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-senhor-dos-aneis.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-use-a-cabeca-java.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-furgeri.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-guerra-dos-tronos.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-machado-de-assis.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-manual-direito-penal.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-musashi.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-o-cacador-de-pipas.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-o-cortico.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-pmi-guide-book.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-senhor-dos-aneis.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-use-a-cabeca-java.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-furgeri.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-guerra-dos-tronos.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-machado-de-assis.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-manual-direito-penal.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-musashi.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-o-cacador-de-pipas.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-o-cortico.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-pmi-guide-book.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-senhor-dos-aneis.jpg' %}" alt="" />
        </div>
        <div class="container-cards-item">
          <img src="{% static 'img\livro-use-a-cabeca-java.jpg' %}" alt="" />
        </div>
      </div>
    </div>
    {% endblock %}

paginas/templates/paginas/rascunho/index copy1.html
{% extends 'paginas/modelo.html' %} 
{% load static %} 

{% block titulo %}
<title>EduTeca</title>
{% endblock %} 

{% block barra %}
{% endblock %}

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

<hr />

<div class="container"
    <div class="row mt-3">
        {% for acervo in livro_list %}
            <div class="cold-md-4">
                <div class="m-3">
                    <h4>{{ acervo.livro.titulo }}</h4>
                    <a href="{% url 'info-livro' acervo.pk %}"><img src="{{ acervo.livro.capa.url }}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %} 

paginas/templates/paginas/rascunho/index funcionando.html
{% extends 'paginas/modelo.html' %} 
{% load static %} 

{% block titulo %}
<title>EduTeca</title>
{% endblock %} 

{% block barra %}
<form action="?" method="GET">

    <input type="text" name="titulo" id="" value="{{ request.GET.titulo }}" class="p-1 border" autocomplete="off" placeholder="Nome ou parte dele">

    <button type="submit" class="btn btn-success">Buscar</button>

    <a href="{% url 'index' %}" class="btn btn-light">Limpar</a>

</form>
{% endblock %}

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

<hr />

<form action="?" method="GET">

    <input type="text" name="titulo" id="" value="{{ request.GET.titulo }}" class="p-1 border" autocomplete="off" placeholder="Nome ou parte dele">

    <button type="submit" class="btn btn-success">Buscar</button>

    <a href="{% url 'index' %}" class="btn btn-light">Limpar</a>

</form>

<div class="col-md-10 mx-auto"> 
    <br>
    <h3>EduTeca - Catálogo de Livros</h3>
    <hr>
    <div>
        {% for livro in object_list %}
        <tr>
            <h4>{{ livro.titulo }}</h4>
            {% if livro.capa %}                             
                <a href="{% url 'info-livro' livro.pk %}"><img src="{{ livro.capa.url }}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
            {% else %}          
                <a href="{% url 'info-livro' livro.pk %}"><img src="{% static 'img/logo.png' %}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
            {% endif %}  
        </tr>  
        {% empty %}
        <tr>
            <td colspan="3"> Nenhum registro identificado!</td>
        </tr>
        {% endfor %}
    </div>

    <ul class="pagination justify-content-center">
    
        {% if page_obj.has_previous %}

            {% if request.GET.nome %}
                <li class="page-item"><a class="page-link" href="?page=1&nome={{request.GET.nome}}">&laquo; Primeira</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&nome={{request.GET.nome}}">Anterior</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
            {% endif %}
        {% endif %}
    
        <li class="page-item">
            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span></li>
    
        {% if page_obj.has_next %}
            {% if request.GET.nome %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&nome={{request.GET.nome}}">Próxima</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&nome={{request.GET.nome}}">Última &raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li>
            {% endif %}
        {% endif %}
    </ul>

</div>
{% endblock %}

paginas/templates/paginas/rascunho/index0.html
{% extends 'paginas/modelo.html' %} 
{% load static %} 

{% block titulo %}
<title>EduTeca</title>
{% endblock %} 

{% block barra %}
{% endblock %}

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

<hr />

<form action="." method="GET" class="form-inline">

    <input type="text" id="" name="titulo" class="p-1 border" autocomplete="off" placeholder="Nome ou parte dele">

    <input type="submit" class="btn btn-primary" value="OK">

</form>

<div class="container"
    <div class="row mt-3">
        {% for livro in livro_list %}
            <div class="cold-md-4">
                <div class="m-3">
                    <h4>{{ livro.titulo }}</h4>
                    <a href="{% url 'info-livro' livro.pk %}"><img src="{{ livro.capa.url }}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %} 

paginas/templates/paginas/rascunho/index1.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block menu %}
<nav class="navbar col-12 position-fixed navbar-expand-lg navbar-dark bg-dark" style="z-index: 999;">
  <div class="container-fluid col-11 m-auto">
    <a class="navbar-brand" href="#">EduTeca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sobre' %}">Projeto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'parceria' %}">Parcerias</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Registros
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Item 01</a></li>
            <li><a class="dropdown-item" href="#">Item 02</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav> 
<br><br>
{% endblock %}

{% block conteudo %}
{% endblock %}

paginas/templates/paginas/rascunho/index2.html
{% extends 'paginas/modelo.html' %} 
{% load static %} 

{% block titulo %}
<title>EduTeca</title>
{% endblock %} 

{% block barra %}
{% endblock %}

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

<hr />

<form action="?" method="GET">

    <input type="text" name="titulo" id="" value="{{ request.GET.titulo }}" class="p-1 border" autocomplete="off" placeholder="Nome ou parte dele">

    <button type="submit" class="btn btn-success">Buscar</button>

    <a href="{% url 'index' %}" class="btn btn-light">Limpar</a>

</form>

<div class="container"
    <div class="row mt-3">
        {% for l in livro_list %}
            <div class="cold-md-4">
                <div class="m-3">
                    <h4>{{ l.titulo }}</h4>
                    <a href="{% url 'info-livro' l.pk %}"><img src="{{ l.capa.url }}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
                </div>
            </div>
        {% endfor %}
</div>
{% endblock %} 

paginas/templates/paginas/rascunho/indexGenero.html
{% extends 'paginas/modelo.html' %} 
{% load static %} 

{% block titulo %}
<title>EduTeca</title>
{% endblock %} 

{% block conteudo %}
{% if request.user.is_authenticated %}
    {% if user.perfil.nome_instituicao %} 
        <h3>Seja bem vindo {{user.perfil.nome_instituicao }}. </h3>
    {% else %} 
        <p>Cadastro imcompleto. Por favor, acesse <a href="{% url 'atualizarDados' %}">Meus Dados</a> para finalizar.</p>
    {% endif %}
{% endif %}

<hr />
<div clas="container">
  {% for genero in generoLivro %}
  <!--Divisão de Livro a partir do Gênero-->


  <h3>{{ genero.descricao }}</h3>
  <div class="row mt-3">
    {% for livro in genero.livro_set.all %}
    <div class="col-md-4 mx-auto">
      <h4>{{ livro.titulo }}</h4>
      <a href="{% url 'info-livro' livro.pk %}"
        ><img
          src="{{ livro.capa.url }}"
          alt=""
          class="img-fluid"
          style="width: 100px; height: 125px; object-fit: cover"
      /></a>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>
{% endblock %} 

paginas/templates/paginas/rascunho/info-livro1.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
    <title>{{ livro.titulo }}</title>
{% endblock %}

{% block carrossel %}
{% endblock %}

{% block conteudo %}
    <h4>{{ livro.titulo }}</h4><hr>
    <img src="{{ livro.capa.url }}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
    <div class="col-md-4 mx-auto">
        <h3>{{ livro.titulo }}</h3>
        <p>ISBN: {{ livro.isbn }} ---- Edição {{ livro.edicao }}</p>
        <p>Autor(a): {{ livro.autor }}</p>
        <p>Ano: {{ livro.ano }} --- Editora {{ livro.editora }}</p>
        <p>Gênero: {{ livro.genero}}</p>
        <hr>
        <p>Resumo: {{ livro.resumo }}</p>
    </div>
{% endblock %}   

paginas/templates/paginas/rascunho/modelo2.html
{% load static %}

<!DOCTYPE html>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<html lang="pt-br">
<head>
    <meta chasert="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block titulo %}
    <title>EduTeca</title>
    {% endblock %}

</head>
<body>

{% block menu %}
<nav class="navbar col-12 position-fixed navbar-expand-lg navbar-dark bg-dark" style="z-index: 999;">
  <div class="container-fluid col-11 m-auto">
    <a class="navbar-brand" href="#">EduTeca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sobre' %}">Projeto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'parceria' %}">Parcerias</a>
        </li>


        {% if request.user.is_authenticated %}


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-user-circle" aria-hidden="true"></i><span id="username">{{ request.user}}</span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Meus dados </a></li>
            <li><a class="dropdown-item" href="#">Alterar Senha</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Sair</a></li>
          </ul>
        </li>


        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Entrar</a>
        </li>

        {% endif %}

      </ul> 
    </div>
  </div>
</nav> 
<br><br>
{% endblock %}

{% block carrosel %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static "img/fatec.jpg" %}" class="img-fluid d-block w-100" alt="..." />
    </div>
    <div class="carousel-item">
      <img src="{% static "img/indaiatuba.jpg" %}" class="img-fluid d-block w-100" alt="..." />
    </div>
    <div class="carousel-item">
      <img src="{% static "img/biblioteca.jpg" %}" class="img-fluid d-block w-100" alt="..." />
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>  
{% endblock %}

<div class="container">
{% block conteudo %}
    <h3>Interface Modelo</h3>

    <p>Conteúdo<p/>
{% endblock %}
</div>

{% block rodape %}
<hr>
<div style="background-color: black;" class="col-11 m-auto">
    <h2 class="text-center">Saiba mais!</h2>
    <div class="col-2 m-auto">
        <a href="http://">
            <i class="fab fa-instagram" style="font-size: 50px;"></i>
        </a>
</div>
<footer class="page-footer font-small blue"
    <div class="text-center">
        <a "">Desenvolvido por </a>
    </div>
</footer>
{% endblock %}

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

paginas/templates/paginas/rascunho/romance.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
    <title>EduTeca</title>
{% endblock %}

{% block conteudo %}
<h2>Romance</h2>

<div clas="container">

    {% for genero in generoRomance %} <!--Divisão de Livro a partir do Gênero-->

    <h3>{{ genero.descricao }}</h3>
    <div class="row mt-3">
        {% for livro in genero.livro_set.all %}
                <div class="col-md-4 mx-auto">
                    <h4>{{ livro.titulo }}</h4>
                    <a href="{% url 'info-livro' livro.pk %}"><img src="{{ livro.capa.url }}" alt="" class="img-fluid" style="width: 100px; height: 125px; object-fit: cover"></a>
                </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block carrosselCatalogo %}
{% endblock %}